# DATA SCIENCE MAJOR PROJECT

## Name : Ayush Kumar Dubey <br>
## Email id : ayushkumardubey10200@gmail.com 

<h4> STEPS

## Importing Required libraries:-

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

## Importing dataset and renaming columns:-

In [2]:
columns=['Age','Workclass','Fnlwgt','Education','education_num','marital_status','occupation','relationship','race','sex','capita_gain','capital_loss','hours_per_week','native_country','income']
df=pd.read_csv("adult.csv",header=None,names=columns)
df

Age          Workclass  Fnlwgt    Education  education_num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            marital_status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capita_gain  capital_loss  hours_per_week  native_country  \
0         Male         2174             0              40   United-States   
1         Male            0             0              13   United-States   
2         Male            0             0              40   United-States   
3         Male            0             0              40   United-States   
4       Female            0             0              40            Cuba   
...        ...          ...           ...             ...             ...   
32556   Female            0             0              38   United-States   
32557     Male            0             0              40   United-States   
32558   Female            0             0              40   United-States   
32559     Male            0             0              20   United-States   
32560   Female        15024             0              40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [3]:
df.columns

Index(['Age', 'Workclass', 'Fnlwgt', 'Education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capita_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income'],
      dtype='object')

In [4]:
df.dtypes

Age                int64
Workclass         object
Fnlwgt             int64
Education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capita_gain        int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

## Handeling null values:-

In [5]:
df.isnull().sum()

Age               0
Workclass         0
Fnlwgt            0
Education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capita_gain       0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

## Handeling Data Columns:-

In [6]:
cat=[x for x in df.columns if df[x].dtype=='object']
cat

['Workclass',
 'Education',
 'marital_status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'native_country',
 'income']

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [8]:
for i in cat:
    df[i]=le.fit_transform(df[i])

In [9]:
df.astype(int)

Age  Workclass  Fnlwgt  Education  education_num  marital_status  \
0       39          7   77516          9             13               4   
1       50          6   83311          9             13               2   
2       38          4  215646         11              9               0   
3       53          4  234721          1              7               2   
4       28          4  338409          9             13               2   
...    ...        ...     ...        ...            ...             ...   
32556   27          4  257302          7             12               2   
32557   40          4  154374         11              9               2   
32558   58          4  151910         11              9               6   
32559   22          4  201490         11              9               4   
32560   52          5  287927         11              9               2   

       occupation  relationship  race  sex  capita_gain  capital_loss  \
0               1             1     4    1         2174             0   
1               4             0     4    1            0             0   
2               6             1     4    1            0             0   
3               6             0     2    1            0             0   
4              10             5     2    0            0             0   
...           ...           ...   ...  ...          ...           ...   
32556          13             5     4    0            0             0   
32557           7             0     4    1            0             0   
32558           1             4     4    0            0             0   
32559           1             3     4    1            0             0   
32560           4             5     4    0        15024             0   

       hours_per_week  native_country  income  
0                  40              39       0  
1                  13              39       0  
2                  40              39       0  
3                  40              39       0  
4                  40               5       0  
...               ...             ...     ...  
32556              38              39       0  
32557              40              39       1  
32558              40              39       0  
32559              20              39       0  
32560              40              39       1  

[32561 rows x 15 columns]

In [10]:
df.dtypes

Age               int64
Workclass         int32
Fnlwgt            int64
Education         int32
education_num     int64
marital_status    int32
occupation        int32
relationship      int32
race              int32
sex               int32
capita_gain       int64
capital_loss      int64
hours_per_week    int64
native_country    int32
income            int32
dtype: object

<h4>In this case we are using income as our y value i.e if income=1 the the income is more than 50K and if income=0 the income is less than or equal to 50K.

## Spliting Train and Test Data:-

In [11]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
print(x.shape)
print(y.shape)
print(type(x))
print(type(y))

(32561, 14)
(32561,)
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [12]:
x.head()

Age  Workclass  Fnlwgt  Education  education_num  marital_status  \
0   39          7   77516          9             13               4   
1   50          6   83311          9             13               2   
2   38          4  215646         11              9               0   
3   53          4  234721          1              7               2   
4   28          4  338409          9             13               2   

   occupation  relationship  race  sex  capita_gain  capital_loss  \
0           1             1     4    1         2174             0   
1           4             0     4    1            0             0   
2           6             1     4    1            0             0   
3           6             0     2    1            0             0   
4          10             5     2    0            0             0   

   hours_per_week  native_country  
0              40              39  
1              13              39  
2              40              39  
3              40              39  
4              40               5

In [13]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: income, dtype: int32

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(22792, 14)
(9769, 14)
(22792,)
(9769,)


In [16]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,precision_score,f1_score

In [17]:
def gen_metrics(ytest,ypred):
    cm=confusion_matrix(ytest,ypred)
    print('confusion matrix\n',cm)
    print('classification report\n',classification_report(ytest,ypred))
    print('acc score',accuracy_score(ytest,ypred))
    print('precision score',precision_score(ytest,ypred))
    print('f1 score',f1_score(ytest,ypred))
    print('Misclassification rate',1-accuracy_score(ytest,ypred))

## Build Models:-

### a. Decision Tree:-

In [18]:
from sklearn.tree import DecisionTreeClassifier

In [19]:
m1=DecisionTreeClassifier(criterion='gini',max_depth=9,min_samples_split=10)
m1.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=9, min_samples_split=10)

In [20]:
print('Training Score',m1.score(x_train,y_train))
print('Testing Score',m1.score(x_test,y_test))

Training Score 0.8664004914004914
Testing Score 0.8492169106356843


In [21]:
ypred_m1=m1.predict(x_test)
print(ypred_m1)

[0 0 0 ... 1 0 0]


In [22]:
gen_metrics(y_test,ypred_m1)

confusion matrix
 [[7011  383]
 [1090 1285]]
classification report
               precision    recall  f1-score   support

           0       0.87      0.95      0.90      7394
           1       0.77      0.54      0.64      2375

    accuracy                           0.85      9769
   macro avg       0.82      0.74      0.77      9769
weighted avg       0.84      0.85      0.84      9769

acc score 0.8492169106356843
precision score 0.7703836930455635
f1 score 0.6356665842196388
Misclassification rate 0.15078308936431573


### b. Random Forest Classifier:-

In [23]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
m2=RandomForestClassifier(n_estimators=60,criterion='entropy',max_depth=9,min_samples_split=10)
m2.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=9, min_samples_split=10,
                       n_estimators=60)

In [25]:
print('Training Score',m2.score(x_train,y_train))
print('Testing Score',m2.score(x_test,y_test))

Training Score 0.8618374868374868
Testing Score 0.8526973078104207


In [26]:
ypred_m2=m2.predict(x_test)
print(ypred_m2)

[0 0 0 ... 1 0 0]


In [27]:
gen_metrics(y_test,ypred_m2)

confusion matrix
 [[7090  304]
 [1135 1240]]
classification report
               precision    recall  f1-score   support

           0       0.86      0.96      0.91      7394
           1       0.80      0.52      0.63      2375

    accuracy                           0.85      9769
   macro avg       0.83      0.74      0.77      9769
weighted avg       0.85      0.85      0.84      9769

acc score 0.8526973078104207
precision score 0.8031088082901554
f1 score 0.6328144934932382
Misclassification rate 0.14730269218957925


### c. Logistic Regression:-

In [28]:
from sklearn.linear_model import LogisticRegression

In [29]:
m3=LogisticRegression(max_iter=1000)
m3.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [30]:
print('Training Score',m3.score(x_train,y_train))
print('Testing Score',m3.score(x_test,y_test))

Training Score 0.7896191646191646
Testing Score 0.7823728119561879


In [31]:
ypred_m3=m3.predict(x_test)
print(ypred_m3)

[0 1 1 ... 1 0 0]


In [32]:
gen_metrics(y_test,ypred_m3)

confusion matrix
 [[6963  431]
 [1695  680]]
classification report
               precision    recall  f1-score   support

           0       0.80      0.94      0.87      7394
           1       0.61      0.29      0.39      2375

    accuracy                           0.78      9769
   macro avg       0.71      0.61      0.63      9769
weighted avg       0.76      0.78      0.75      9769

acc score 0.7823728119561879
precision score 0.6120612061206121
f1 score 0.39013195639701664
Misclassification rate 0.2176271880438121


### d. KNN classifier:-

In [33]:
from sklearn.neighbors import KNeighborsClassifier

In [34]:
m4=KNeighborsClassifier(n_neighbors=12)
m4.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=12)

In [35]:
print('Training Score',m4.score(x_train,y_train))
print('Testing Score',m4.score(x_test,y_test))

Training Score 0.808046683046683
Testing Score 0.7949636605589109


In [36]:
ypred_m4=m4.predict(x_test)
print(ypred_m4)

[0 0 0 ... 1 0 0]


In [37]:
gen_metrics(y_test,ypred_m4)

confusion matrix
 [[7247  147]
 [1856  519]]
classification report
               precision    recall  f1-score   support

           0       0.80      0.98      0.88      7394
           1       0.78      0.22      0.34      2375

    accuracy                           0.79      9769
   macro avg       0.79      0.60      0.61      9769
weighted avg       0.79      0.79      0.75      9769

acc score 0.7949636605589109
precision score 0.7792792792792793
f1 score 0.34133508714238736
Misclassification rate 0.20503633944108912


### e. SVC classifier(with linear kernel)

In [38]:
from sklearn.svm import LinearSVC

In [39]:
m5=LinearSVC(C=1.0)
m5.fit(x_train,y_train)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC()

In [40]:
print('Training Score',m5.score(x_train,y_train))
print('Testing Score',m5.score(x_test,y_test))

Training Score 0.8008950508950509
Testing Score 0.7962944006551336


In [41]:
ypred_m5=m5.predict(x_test)
print(ypred_m5)

[0 0 0 ... 1 0 0]


In [42]:
gen_metrics(y_test,ypred_m5)

confusion matrix
 [[7298   96]
 [1894  481]]
classification report
               precision    recall  f1-score   support

           0       0.79      0.99      0.88      7394
           1       0.83      0.20      0.33      2375

    accuracy                           0.80      9769
   macro avg       0.81      0.59      0.60      9769
weighted avg       0.80      0.80      0.75      9769

acc score 0.7962944006551336
precision score 0.8336221837088388
f1 score 0.32588075880758804
Misclassification rate 0.20370559934486643


## Selecting model with best accuracy:-

In [43]:
lst=[accuracy_score(y_test,ypred_m1),accuracy_score(y_test,ypred_m2),accuracy_score(y_test,ypred_m3),accuracy_score(y_test,ypred_m4),accuracy_score(y_test,ypred_m5)]

In [44]:
cas=pd.Series(lst,index=['Decision Tree Classifier','Random Forest Classifier','Logistic Regression','KNN Classifier','SVM Classifier'])
cas

Decision Tree Classifier    0.849217
Random Forest Classifier    0.852697
Logistic Regression         0.782373
KNN Classifier              0.794964
SVM Classifier              0.796294
dtype: float64

In [45]:
bm_as =cas.max()
bm_as

0.8526973078104207

In [46]:
bm_name = cas[cas == bm_as].index[0]

In [47]:
bm_name

'Random Forest Classifier'

## Misclassification Rate:-

Misclassification Rate=1-accuracy_score

In [48]:
lst_mis=[1-accuracy_score(y_test,ypred_m1),1-accuracy_score(y_test,ypred_m2),1-accuracy_score(y_test,ypred_m3),1-accuracy_score(y_test,ypred_m4),1-accuracy_score(y_test,ypred_m5)]

In [49]:
mcr=pd.Series(lst_mis,index=['Decision Tree Classifier','Random Forest Classifier','Logistic Regression','KNN Classifier','SVM Classifier'])
mcr

Decision Tree Classifier    0.150783
Random Forest Classifier    0.147303
Logistic Regression         0.217627
KNN Classifier              0.205036
SVM Classifier              0.203706
dtype: float64

## Reporting best model:-

In [50]:
print('The best module for given dataset out of all five is :', bm_name,' having accuracy score of ',bm_as)

The best module for given dataset out of all five is : Random Forest Classifier  having accuracy score of  0.8526973078104207
